# Generated by Django 5.1 on 2024-09-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cpc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ctr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
