# Generated by Django 5.1 on 2024-09-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignTracker', '0003_campaign_user_friendly_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='type',
        ),
    ]
