# Generated by Django 5.1 on 2024-09-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignTracker', '0004_remove_campaign_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='user_friendly_name',
            new_name='product',
        ),
    ]
