# Generated by Django 5.1 on 2024-09-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignTracker', '0005_rename_user_friendly_name_campaign_product'),
    ]

    operations = [
    ]
