# Generated by Django 5.1 on 2024-09-04 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignTracker', '0006_auto_20240904_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('month', models.DateField()),
                ('target_spend', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_impressions', models.IntegerField()),
                ('target_clicks', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CampaignTracker.client')),
            ],
        ),
    ]
