# Generated by Django 5.1 on 2024-09-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignTracker', '0007_target'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'ordering': ['month', 'product', 'campaign_type']},
        ),
        migrations.AddField(
            model_name='target',
            name='campaign_type',
            field=models.CharField(choices=[('Video', 'Video'), ('Display', 'Display'), ('Search', 'Search')], default='Display', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='target',
            unique_together={('product', 'month', 'client', 'campaign_type')},
        ),
    ]
