# Generated by Django 5.1 on 2024-09-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignTracker', '0008_alter_target_options_target_campaign_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='conversions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
