# Generated by Django 5.1 on 2024-09-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignTracker', '0009_alter_campaign_conversions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='channel',
            field=models.CharField(choices=[('Google', 'Google'), ('Stackadapt', 'Stackadapt')], default='Google', max_length=20),
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
